data:
  train_path: 'data/pickled_data_train.pkl'
  test_path: 'data/pickled_data_test.pkl'
  batch_size: 16
  # Tokenizing large amounts of data takes time. Save if you want
  pickle_data: True

train:
  epochs: 25
  lr: 1e-5
  validation_split: 0.1
  # Balance training data for equal class sizes. 0: Oversample, 1: Prune, 2: None
  balance_mode: 0

model:
   # Criteria to save best model. 0: Min val loss. 1: Max F1 score
  save_mode: 1
  save_path: 'model/m_saved_state_dict.pt'
  # Train new model or work with existing model
  load_train: False
  # Path for training or testing existing model
  load_path: 'model/m_state_dict_optimized_v00.pt'
  # 0: Train. 1: Test, 2: Get embeddings, 3: OOD Test, 4: Optimize embedding space
  model_mode: 3
  num_outputs: 100
